name: Daily SEO Post
on:
  schedule:
    - cron: '0 9 * * *'   # runs at 9:00 UTC daily
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run main
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          EBAY_APP_ID: ${{ secrets.EBAY_APP_ID }}
          EBAY_SANDBOX_APP_ID: ${{ secrets.EBAY_SANDBOX_APP_ID }}
          EBAY_USE_SANDBOX: 'false'
          WORDPRESS_SITE: ${{ secrets.WORDPRESS_SITE }}
          WP_COM_TOKEN: ${{ secrets.WP_COM_TOKEN }}
        run: python main.py
